language: c++

env:
  global:
    - CXX_FLAGS="-Wall -pedantic -Werror -Wno-variadic-macros -Wno-long-long -Wno-shadow"
    - CMAKE_GENERATOR="Unix Makefiles"

matrix:
  include:
    - os: linux
      dist: focal
      sudo: true
      compiler:
        - gcc
        - clang
        - ninja-build
        - cmake
        - cmake-data

before_install:
  # Combine global build options with OS/compiler-dependent options
  - export CMAKE_OPTIONS=${CMAKE_OPTIONS}" "${ENV_CMAKE_OPTIONS}
  - export CXX_FLAGS=${CXX_FLAGS}" "${ENV_CXX_FLAGS}

install:
  - if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  - echo ${PATH}
  - echo ${CXX}
  - echo ${CMAKE_GENERATOR}
  - ${CXX} --version
  - ${CXX} -v

addons:
  apt:
    packages:
      - cmake-data
      - cmake
  sonarcloud:
    organization: "bluelineio"
    secure: "G2+daSxEfGil/ZgvPJHTREZyT4Y/eq55PeZ5mMrNPHMwSrMCCDaX58CZUCpShsJSNbxPXynlPGS2RQ13RYBdESsh3tTvztNcQ0qhiCduRy8EBqNlSrWGYL4w3mgyC/GrNziaOJjdh6ViVZuwIcEsLEpyEp3h4H8s95IHQjv9TZw9pzvQp971XL+yXJXlsjETi1erLJNAEJl8xp8mrdjq0xqIIjFAGDG6bY8dNbjIl6Q2qeA7lENQghfSzVsufkcLDF6Y2v4X2hC+/xmo9bBGlD3IK1fF5TrOJpyIKZzkCVWVxmWxRaDsLo6hgVRm8tOw6kXWUraYF4AkSHzIfKR/+g041W31+eimjMXZuHXXslXhcEgjIJ5lCWUcwFmwSy12uOkTeFPleIOBri/VZE8QbKgES6eZajNIKRECvOHYuzl2+6gEZL6tKXZ50sMA9vjMMQBZ/rBVfojfX+4mNktjQAL+lWK4cLMHKQRt+8VgxlfUKtBu3TZzy8JTA4IfEf3mYDQnVJmCPPHd1192eE7Phu1vXCbAUB5jfKzSymYUTQz6cXJuz+IThrr6GixXPfPSLfpKdbDXMHdGk6gjOg/d574c9Oy+qh61h8rp9ie4ZFuAUjpzG0GmHr98Vctc77rwhsQWrcJTxt+baiw5ojvHXbiSml2xrpvA1bp/nXYWEKU="

script:
  # Wraps the compilation with the Build Wrapper to generate configuration (used
  # later by the SonarScanner) into the "bw-output" folder
  - mkdir -p build
  - cd build
  - cmake ${CMAKE_OPTIONS} -G "${CMAKE_GENERATOR}" -DCMAKE_CXX_FLAGS=${CXX_FLAGS} -DBUILD_TESTS=ON ..
  - ninja
  #- build-wrapper-linux-x86-64 --out-dir bw-output cmake --build build/
  # And finally run the SonarCloud analysis - read the "sonar-project.properties"
  # file to see the specific configuration
  - sonar-scanner
